language: python
python:
    - "2.7"
    - "3.5"
sudo: required
services:
    - docker
env:
    - NC_VERSION=12
    - NC_VERSION=11

before_install:
    - travis-build/setup_nc_docker.sh $NC_VERSION

install:
    - pip install requests unittest-data-provider six

script:
    - cp owncloud/test/config.py.sample owncloud/test/config.py
    # execute unit tests
    - ./runtests.sh

